//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeoApiReport.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GeoApiReport.Core.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://cs-interview-geolocation.azurewebsites.net/api/GeolocationFunction?code=h/0av4gxkkTRz6d5HFIKr/U3b4ynT/CCNiKuHI7Wk7pVWYBKS8iZOw==.
        /// </summary>
        public static string SITE_URL_ADDRESSES {
            get {
                return ResourceManager.GetString("SITE_URL_ADDRESSES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://cs-interview-users-as.azurewebsites.net/api/UserDataFunction?code=wUi5HeaRJtYjX/7APOVehBWvLLaOYI7VFJBRCCX5tmk6i2aOoe0nkA==.
        /// </summary>
        public static string SITE_URL_USERS_AS {
            get {
                return ResourceManager.GetString("SITE_URL_USERS_AS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://cs-interview-users-eu.azurewebsites.net/api/UserDataFunction?code=GjLpRZ2u2ZNoNi0Rrvdl6PSF3XEWUgJUY8e6BqUOhgx9e5KRISJuQA==.
        /// </summary>
        public static string SITE_URL_USERS_EU {
            get {
                return ResourceManager.GetString("SITE_URL_USERS_EU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://cs-interview-users-us.azurewebsites.net/api/UserDataFunction?code=Ax1P8UqUd6sQtQpJ4ldX8wbh/cEXt6xDFO4IK3ptTlDC29KlGHyj6A==.
        /// </summary>
        public static string SITE_URL_USERS_US {
            get {
                return ResourceManager.GetString("SITE_URL_USERS_US", resourceCulture);
            }
        }
    }
}
